document.writeln(" <div class=\"sidebar\">");
document.writeln("        <!--快捷按钮组-->");
document.writeln("        <div class=\"sidebarshorcuts\">");
document.writeln("            <button class=\"btn btn-success\"><i class=\"fa fa-signal\"></i></button>");
document.writeln("            <button class=\"btn btn-info\"><i class=\"fa fa-pencil\"></i></button>");
document.writeln("            <button class=\"btn btn-warning\"><i class=\"fa fa-group\"></i></button>");
document.writeln("            <button class=\"btn btn-danger\"><i class=\"fa fa-cogs\"></i></button>");
document.writeln("        </div>");
document.writeln("        <!--列表导航-->");
document.writeln("        <ul class=\"navlist\">");
document.writeln("            <li><a href=\"\"><i class=\"fa fa-dashboard fatest\"></i>控制台</a></li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\"><i class=\"fa fa-desktop fatest\"></i>我们 <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                <ul class=\"submenu\">");
document.writeln("                    <li><a href=\"\">公司简介</a></li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\"\">企业文化 <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                        <ul class=\"submenu\">");
document.writeln("                            <li><a href=\"\">视频集</a></li>");
document.writeln("                            <li><a href=\"\">列表文章</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li><a href=\"\">联系我们</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\"><i class=\"fa fa-list fatest\"></i>动态 <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                <ul class=\"submenu\">");
document.writeln("                    <li><a href=\"\">行业动态</a></li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\"\">活动 <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                        <ul class=\"submenu\">");
document.writeln("                            <li><a href=\"\">投票</a></li>");
document.writeln("                            <li><a href=\"\">图片互动</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li><a href=\"\">公司新闻</a></li>");
document.writeln("                    <li><a href=\"\">往期回顾</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\"><i class=\"fa fa-user fatest\"></i>人才 <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                <ul class=\"submenu\">");
document.writeln("                    <li><a href=\"http://www.baidu.com\">人才招聘</a></li>");
document.writeln("                    <li><a href=\"\">人才理念</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");