document.writeln("  <div class=\"header navbar clearfix\">");
document.writeln("        <div class=\"left\">");
document.writeln("            <i class=\"fa fa-globe\"></i><h1>中慧集团</h1>");
document.writeln("        </div>");
document.writeln("        <div class=\"right clearfix\">");
document.writeln("            <ul class=\"nav clearfix\">");
document.writeln("                <li class=\"grey\">");
document.writeln("                    <a href=\"\">");
document.writeln("                        <i class=\"fa fa-tasks\"></i>");
document.writeln("                        <span class=\"badge badge-grey\">4</span>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li class=\"purple\">");
document.writeln("                    <a href=\"\">");
document.writeln("                        <i class=\"fa fa-tasks\"></i>");
document.writeln("                        <span class=\"badge badge-purple\">4</span>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li class=\"green\">");
document.writeln("                    <a href=\"\">");
document.writeln("                        <i class=\"fa fa-tasks\"></i>");
document.writeln("                        <span class=\"badge badge-green\">4</span>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li class=\"light-blue\">");
document.writeln("                    <a href=\"#\" class=\"useraction\">");
document.writeln("                        <img class=\"user-photo\" src=\"/wechat-subscribe-master/common/img/user.jpg\" alt=\"Jason\'s Photo\">");
document.writeln("                        <span class=\"user-info\">");
document.writeln("                            <small>欢迎您,</small>Jason");
document.writeln("                        </span>");
document.writeln("                        <i class=\"fa fa-caret-down\"></i>");
document.writeln("                    </a>");
document.writeln("                    <ul class=\"usermenu\">");
document.writeln("                        <li><a href=\"editpwd.html\"><i class=\"fa fa-key\"></i>修改密码</a></li>");
document.writeln("                        <hr/>");
document.writeln("                        <li><a href=\"\"><i class=\"fa fa-power-off\"></i>退出</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");/**
 * Created by sun on 2015/9/29.
 */
