document.writeln(" <div class=\"sidebar\">");
document.writeln("        <!--快捷按钮组-->");
document.writeln("        <div class=\"sidebarshorcuts\">");
document.writeln("            <button class=\"btn btn-success\"><i class=\"fa fa-signal\"></i></button>");
document.writeln("            <button class=\"btn btn-info\"><i class=\"fa fa-pencil\"></i></button>");
document.writeln("            <button class=\"btn btn-warning\"><i class=\"fa fa-group\"></i></button>");
document.writeln("            <button class=\"btn btn-danger\"><i class=\"fa fa-cogs\"></i></button>");
document.writeln("        </div>");
document.writeln("        <!--列表导航-->");
document.writeln("        <ul class=\"navlist\">");
document.writeln("            <li><a href=\"index.html\"><i class=\"fa fa-dashboard fatest\"></i>控制台</a></li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\"><i class=\"fa fa-desktop fatest\"></i>图文发布</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\"><i class=\"fa fa-list fatest\"></i>菜单编辑</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\"><i class=\"fa fa-user fatest\"></i>文章列表<i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                <ul class=\"submenu\">");
document.writeln("                    <li><a href=\"articlelist.html?modeId=1\">公司新闻</a></li>");
document.writeln("                    <li><a href=\"articlelist.html?modeId=2\">行业动态</a></li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\"\">企业文化 <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                        <ul class=\"submenu\">");
document.writeln("                            <li><a href=\"articlelist.html?modeId=3\">列表文章</a></li>");
document.writeln("                            <li><a href=\"articlelist.html?modeId=4\">故事集</a></li>");
document.writeln("                            <li><a href=\"articlelist.html?modeId=5\">视频集</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\"\">人才管理 <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                        <ul class=\"submenu\">");
document.writeln("                            <li><a href=\"articlelist.html?modeId=6\">人才招聘</a></li>");
document.writeln("                            <li><a href=\"articlelist.html?modeId=7\">人才理念</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\"><i class=\"fa fa-cog fatest\"></i>活动管理 <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                <ul class=\"submenu\">");
document.writeln("                    <li><a href=\"\">用户管理</a></li>");
document.writeln("                    <li><a href=\"editpwd.html\">修改密码</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");